Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -18,37 +18,37 @@ jobs:
     - name: Checkout Repository
       uses: actions/checkout@v2
 
-   # - name: Login to Docker Hub
-   #   uses: docker/login-action@v1
-   #   with:
-   #     username: ${{ secrets.DOCKER_USERNAME }}
-   #     password: ${{ secrets.DOCKER_PASSWORD }}
+    - name: Login to Docker Hub
+      uses: docker/login-action@v1
+      with:
+       username: ${{ secrets.DOCKER_USERNAME }}
+       password: ${{ secrets.DOCKER_PASSWORD }}
 
-   # - name: Build Docker Image
-    #  run: |
-   #     docker build -t javialroro/snupieencuestas:latest .
+    - name: Build Docker Image
+      run: |
+        docker build -t javialroro/snupieencuestas:latest .
       
-    #- name: Push Docker Image
-    #  run: |
-    #    docker push javialroro/snupieencuestas:latest
-
-    - name: Start Docker Compose
+    - name: Push Docker Image
       run: |
-        docker-compose up -d
-        sleep 80 # Espera 30 segundos para que los servicios se inicien
-    - name: Run Tests
-      run:  |
-        docker-compose exec app npm test
-        TEST_EXIT_CODE=$?
-        echo "Test exit code: $TEST_EXIT_CODE"
+        docker push javialroro/snupieencuestas:latest
 
-    - name: Stop Docker Compose
-      run: |
-        docker-compose down
+    # - name: Start Docker Compose
+    #   run: |
+    #     docker-compose up -d
+    #     sleep 80 # Espera 30 segundos para que los servicios se inicien
+    # - name: Run Tests
+    #   run:  |
+    #     docker-compose exec app npm test
+    #     TEST_EXIT_CODE=$?
+    #     echo "Test exit code: $TEST_EXIT_CODE"
+
+    # - name: Stop Docker Compose
+    #   run: |
+    #     docker-compose down
         
-    - name: Check Test Result
-      run: |
-        if [ $TEST_EXIT_CODE -ne 0 ]; then
-          echo "Tests failed, cancelling merge."
-          exit 1
-        fi
+    # - name: Check Test Result
+    #   run: |
+    #     if [ $TEST_EXIT_CODE -ne 0 ]; then
+    #       echo "Tests failed, cancelling merge."
+    #       exit 1
+    #     fi
