Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -21,8 +21,8 @@ jobs:
     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
-       username: ${{ secrets.DOCKER_USERNAME }}
-       password: ${{ secrets.DOCKER_PASSWORD }}
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
 
     - name: Build Docker Image
       run: |
@@ -36,5 +36,7 @@ jobs:
       run: |
         chmod +x node_modules/.bin/jest
         npx jest --testPathPattern=testUnitarios.js
-
-
+        if [ $? -ne 0 ]; then
+          echo "Unit tests failed. Aborting push."
+          exit 1
+        fi
